"""Remove Locations table

Revision ID: 025e7762c7a1
Revises: a4a5eca457cc
Create Date: 2024-03-03 02:25:56.967198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025e7762c7a1'
down_revision = 'a4a5eca457cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Locations_id', table_name='Locations')
    op.drop_table('Locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Locations_id', 'Locations', ['id'], unique=False)
    # ### end Alembic commands ###
