"""seed categories

Revision ID: a4a5eca457cc
Revises: c41b511fbfb8
Create Date: 2024-02-28 22:38:00.098478

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4a5eca457cc"
down_revision = "c41b511fbfb8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.Table(
            "Categories", sa.MetaData(), sa.Column("title", sa.String(), nullable=False)
        ),
        [
            {"title": "SHOPPING"},
            {"title": "TRAVEL"},
            {"title": "ENTERTAINMENT"},
            {"title": "SOCIAL"},
            {"title": "SPORTS"},
            {"title": "ANIMALS"},
            {"title": "MUSIC"},
            {"title": "CUISINE"},
            {"title": "BEAUTY"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM Categories")
    # ### end Alembic commands ###
