"""Remove History Table

Revision ID: c41b511fbfb8
Revises: ded258c274e1
Create Date: 2024-02-25 22:27:36.139740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41b511fbfb8'
down_revision = 'ded258c274e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('History_Categories')
    op.drop_index('ix_Histories_id', table_name='Histories')
    op.drop_table('Histories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('visit_time', sa.DATETIME(), nullable=False),
    sa.Column('time_spent', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('producer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['Producers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Histories_id', 'Histories', ['id'], unique=False)
    op.create_table('History_Categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('consumer_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['Histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
