"""Remove name from producer and consumer table

Revision ID: ded258c274e1
Revises: cd497bf086e5
Create Date: 2024-02-24 22:28:02.745199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded258c274e1'
down_revision = 'cd497bf086e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Consumers', 'name')
    op.drop_column('Producers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Producers', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('Consumers', sa.Column('name', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
