"""Create ProducerInterests table

Revision ID: fa20d9f16bb5
Revises: a4a5eca457cc
Create Date: 2024-02-29 23:41:58.542487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa20d9f16bb5'
down_revision = 'a4a5eca457cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Producer_Interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['Producers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_Locations_id', table_name='Locations')
    op.drop_table('Locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Locations_id', 'Locations', ['id'], unique=False)
    op.drop_table('Producer_Interests')
    # ### end Alembic commands ###
